Repository 2025-BLAYBUS-TEAM-hairGGmalza/hairGGmalza-client, pull requests merged in 2025-02, with the labels that each got.

#5 FEAT: 공통 컴포넌트 구현
  public/Logo.png
  src/app/globals.css
  src/app/page.module.css
  src/app/page.tsx
  src/app/report/page.tsx
  src/components/common/Header/DesignerHeader.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/MainHeader.tsx
  src/components/common/Header/PaymentHeader.tsx
  src/components/common/Header/SearchHeader.tsx
  src/components/common/Header/StyledFichevronLeft.tsx
  src/components/common/Navbar/Navbar.tsx
  src/hooks/useBackNavigation.ts
  src/hooks/useNavigateTo.ts
Labels: feat, zza_lng

#7 Feat/#4/designer page
  public/images/heart.png
  public/images/review-example.jpeg
  public/images/scissors.png
  public/images/shareButton.png
  src/app/designer/[id]/page.tsx
  src/app/globals.css
  src/components/ReviewAndPortfolio.tsx
Labels: feat, suzzang2

#6 Feat/#2/bottom modal
  src/app/register/page.tsx
  src/components/BottomModal.tsx
  src/components/CenterModal.tsx
Labels: feat, suzzang2

#9 Refactor/bottom button
  public/Logo.png
  public/images/heart.png
  public/images/review-example.jpeg
  public/images/scissors.png
  public/images/shareButton.png
  src/app/designer/[id]/page.tsx
  src/app/globals.css
  src/app/page.module.css
  src/app/page.tsx
  src/app/register/page.tsx
  src/app/report/page.tsx
  src/components/ReviewAndPortfolio.tsx
  src/components/common/BottomButtonBar.tsx
  src/components/common/BottomModal.tsx
  src/components/common/CenterModal.tsx
  src/components/common/Header/DesignerHeader.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/MainHeader.tsx
  src/components/common/Header/PaymentHeader.tsx
  src/components/common/Header/SearchHeader.tsx
  src/components/common/Header/StyledFichevronLeft.tsx
  src/components/common/Navbar/Navbar.tsx
  src/hooks/useBackNavigation.ts
  src/hooks/useNavigateTo.ts
Labels: enhancement, suzzang2

#12 Feat/#10/review page
  src/app/designer/[id]/page.tsx
  src/app/designer/[id]/review/page.tsx
Labels: feat, suzzang2

#15 Feat/#11/register bottom modal
  package-lock.json
  package.json
  src/app/designer/[id]/Calendar.css
  src/app/designer/[id]/page.tsx
  src/app/signup/page.tsx
  src/components/common/BottomModal.tsx
Labels: feat, suzzang2

#17 Feat/#8/filter bottom modal
  src/app/globals.css
  src/components/common/BottomModal.tsx
  src/components/common/Divider.tsx
  src/components/common/Header/DesignerHeader.tsx
  src/components/filter/ConsultingFilter.tsx
  src/components/filter/ExpertiseFilter.tsx
  src/components/filter/FilterModal.tsx
  src/components/filter/HairInfoFilter.tsx
  src/components/filter/PriceFilter.tsx
  src/components/filter/RegionFilter.tsx
  src/components/filter/TabBar.tsx
  src/components/search/SearchCard.tsx
Labels: feat, zza_lng

#31 Feat/edits2 - reservation 페이지 완성
  src/apis/apiTest.ts
  src/app/designer/[id]/page.tsx
  src/app/main/page.tsx
  src/app/reservation/[id]/page.tsx
  src/app/reservation/page.tsx
  src/app/test/page.tsx
  src/components/common/Profile.tsx
  src/components/common/Tag.tsx
Labels: feat, suzzang2
